### ISSUE TITLE
Side screw dimensions

### ISSUE THREAD

**Issue by mhuesch** [rothgar/ergodox-ez-tent-kit#2]
Hi @rothgar! Love your kit - thanks so much for sharing it. I just ordered one from a vendor via Thingiverse (sent you a tip 🙂) and am eagerly anticipating receiving it.

I was wondering, though, what the dimensions of the side screws are (you're using 3 screws on each keyboard-half, I believe, to hold them onto the top piece of the tent-kit). I have searched around and haven't found the specs on the Ergodox-EZ website, or elsewhere on the internet.

Do you know the dimensions of the screws are? Assuming they're standard parts it'd be cheaper to avoid purchasing the Ergodox-EZ tent kit, just to get the screws.

Thanks again, and apologies if the screw info is out there and I missed it.

**Comment by rothgar** [comment]
Sorry for the delay. I actually bought a screw gauge and emailed ergodox to find the dimensions.

The screws are M3 thread, 36 steps (meaning each step is 10 degrees). The threads are about 5mm long.

Ergodox will send you replacement screws for $20 (with springs) but I'm sure you can find them cheaper at a hardware store.

**Comment by mhuesch** [comment]
No problem, thanks so much for the info.
